                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                    
                                                                                                          !                                                                                                                                         
                                                                                                          function                                                                                                                                  
                                                                                                        ( a,                                                                                                                                        
                                                                                                        b) {                                                                                                                                        
                                                                                                        "obje"                                                                                                                                      
                                                                                                        + "ct"                                                                                                                                      
                                                                                                        ==                                                                                                                                          
                                                                                                        typeof                                                                                                                                      
                                                                                                        module    &&                                                                                                                                
                                                                                                          "obje"+ "ct"                                                                                                                              
                                                                                                          ==     typeof                                                                                                                             
                                                                                                            module       .                                                                                                                          
                                                                                                            exports      ?        module                                                                                                            
                                                                                                              . exports =a .        document                                                                                                        
                                                                                                                ?  b(a,!0 ):        function                                                                                                        
                                                                                                                    (a){if (!a        .                                                                                                             
                                                                                                                      document        ) throw                                                                                                       
                                                                                                                        new           Error  (                                                                                                      
                                                                                                                          "jQue"        + "ry r"                                                                                                    
                                                                                                                          +             "equi" +                                                                                                    
                                                                                                                            "res "      + "a wi"                                                                                                    
                                                                                                                                      +"ndow"  +                                                                                                    
                                                                                                                                      " wit"   +                                                                                                    
                                                                                                                                      "h a "   +                                                                                                    
                                                                                                                                      "docu"     +                                                                                                  
                                                                                                                                        "ment")    ;                                                                                                
                                                                                                                      return            b(a)} :b( a)}(                                                                                              
                                                                                                                        "unde"   +        "fine"  + "d" !=                                                                                          
                                                                                                                          typeof          window?window :this,                                                                                      
                                                                                                                            function        (a,b){ var c=[],d=c.                                                                                    
                                                                                                                              slice ,e          =c. concat, f= c .                                                                                  
                                                                                                                              push ,g=            c. indexOf,h={},                                                                                  
                                                                                                                                i=  h.              toString, j  =h.                                                                                
                                                                                                                                hasOwnProperty      ,k={}, l="1.11"+                                                                                
                                                                                                                                ".2",   m=          function( a , b ){                                                                              
                                                                                                                                return            new m.fn .init(a,b)}                                                                              
                                                                                                                                ,   n                                =                                                                              
                                                                                                                                /^[\s\uFEFF\xA0]+|[\s\uFEFF\xA0]+$/g ,                                                                              
                                                                                                                                o=/^-ms-/,p =/-([\da-z])/gi,q=function                                                                              
                                                                                                                                (a,b){ return b.toUpperCase()};m.fn=                                                                                
                                                                                                                                  m.prototype= {jquery:l,constructor                                                                                
                                                                                                                                  : m,selector: ,length:0,toArray:                                                                                  
                                                                                                                                    function(){return d.call (this                                                                                  
                                                                                                                                    )},get:function(  a){return                                                                                     
                                                                                                                                      null!= a?0>a?this [a+this.                                                                                    
                                                                                                                                          length] :this[ a]:  d.                                                                                    
                                                                                                                                        call   (   this )} ,                                                                                        
                                                                                                                                        pushStack:function (                                                                                        
                                                                                                                                      a) {var  b=m .merge(                                                                                          
                                                                                                                                    this. constructor(),                                                                                            
                                                                                                                                    a   ) ;return     b.                                                                                            
                                                                                                                                prevObject  =this,  b.                                                                                              
                                                                                                                          context= this.context,b },                                                                                                
                                                                                                                    each:function   (a,b){ return m.                                                                                                
                                                                                                                  each(this,a,b)}, map:function(a)                                                                                                  
                                                                                                                {return   this.pushStack(m. map(                                                                                                    
                                                                                                              this       ,    function(b,c )   {                                                                                                    
                                                                                                              return a   .      call (b,c,b)}))}                                                                                                    
                                                                                                            ,slice: function    (){ return this.                                                                                                    
                                                                                                          pushStack( d    .         apply( this,                                                                                                    
                                                                                                          arguments ))      }    ,    first      :                                                                                                  
                                                                                                        function (    ){    return this.eq( 0)  },                                                                                                  
                                                                                                      last  :function(){        return this.eq(- 1                                                                                                  
                                                                                                      ) },eq:function(    a) {    var    b =this .                                                                                                  
                                                                                                    length,c =+a+(0>        a?b:0); return this.                                                                                                    
                                                                                                  pushStack (c >=0    && b    >c?[this[c]]: [])}                                                                                                    
                                                                                                  ,end: function()    {       return     this.                                                                                                      
                                                                                                prevObject ||  this.    constructor (null)},push :                                                                                                        
                                                                                              f,sort:c.sort, splice:c.      splice} ,   m  .                                                                                                        
                                                                                              extend=m .fn      .       extend=function ()                                                                                                          
                                                                                            {var a, b,c,d,      e ,f    ,g=arguments[0 ]                                                                                                            
                                                                                          ||  {}   ,   h =1,i=    arguments .length ,j=!1  ;                                                                                                            
                                                                                          for  (   "bool"+            "ean"==typeof  g                                                                                                              
                                                                                        &&( j   =g ,  g=          arguments [h]||{},                                                                                                                
                                                                                      h++ ) ,"obje"  +    "ct"    ==typeof   g|| m .                                                                                                                
                                                                                      isFunction    (g )  || (g=  {} ),h ===i&&(g=                                                                                                                  
                                                                                    this ,h--);i      >           h;h++) if(null                                                                                                                    
                                                                                  != (e=arguments[h]            ))for(d in  e)a=                                                                                                                    
                                                                                  g[d],c=e[d] ,g!==c&&      (j&&c &&     (  m.                                                                                                                      
                                                                                isPlainObject( c        )     ||  (b=m     .                                                                                                                        
                                                                              isArray(c)) )?(b    ?( b    =!  1 ,f =a&&m .                                                                                                                          
                                                                              isArray( a  )? a    :[ ]):  f   = a   &&m  .                                                                                                                          
                                                                            isPlainObject   (     a) ?    a : {},g[d]=m.                                                                                                                            
                                                                          extend(j ,f,        c         )):void  0!==c                                                                                                                              
                                                                        && (g[d ]=c))  ;          return g}, m.extend(                                                                                                                              
                                                                        {expando :    "jQue"  +     "ry" +( l+ Math.                                                                                                                                
                                                                        random( ))        .     replace ( /\D/g    ,),                                                                                                                                  
                                                                          isReady                 :!0  ,  error  :                                                                                                                                  
                                                                          function (      a     )  {  throw new                                                                                                                                     
                                                                            Error(a )} ,    noop:function (){}                                                                                                                                      
                                                                              , isFunction    :function(  a ){                                                                                                                                      
                                                                                return "func"+ "tion" ===m .                                                                                                                                        
                                                                                  type (a)},isArray:Array.                                                                                                                                          
                                                                                    isArray||function( a){                                                                                                                                          
                                                                                        return  "arra" +                                                                                                                                            
                                                                                            "y"  ===m.                                                                                                                                              
                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                    




